### ISSUE TITLE
Authorization error when accessing app from consumer tenant

### ISSUE THREAD

**Issue by johnkbarrow** [SAP-samples/cloud-cap-samples-java#232] opened 2023-06-01 12:54 UTC
Have deployed the app to BTP CF provider subaccount, created consumer subaccount, and successfully subscribed to the application. However, whenever I try to access the application from the consumer subaccount, I get the error "The redirect_uri has an invalid domain."
The URL left in the browser window is: https://c1.authentication.eu20.hana.ondemand.com/oauth/authorize?response_type=code&client_id=sb-bookshop-mt-cpt_p1-s1!t29749&redirect_uri=https%3A%2F%2Fc1-cpt-p1-s1-bookshop-mt-app.cfapps.eu20-001.hana.ondemand.com%2Flogin%2Fcallback

**Comment by johnkbarrow** [comment] 2023-06-01 12:58
Is it related to this perhaps? https://me.sap.com/notes/0002864831

**Comment by beckermarc** [comment] 2023-06-01 13:30
Hm, seems like the difference in the two domains could cause the problem here:
- eu20.hana.ondemand.com
- eu20-001.hana.ondemand.com
I think this doesn't seem to be an issue of the sample, but rather of the BTP landscape itself.

There seems to be an inconsistency in the domain used for the authentication URL of XSUAA (taken from the XSUAA service binding) and the domain used for the application routes (chosen during MTA deployment), which causes this redirect_uri error. I guess actually XSUAA should be preconfigured on that landscape to also allow eu20-001 domains, if they are used by the landscape. But that doesn't seem to be the case.

You can explicitly add the relevant information to your xs-security-mt.json (as you deploy the MT variant of the sample) as also suggested in the note you linked above:

```
"oauth2-configuration": {
    "redirect-uris": ["https://*.cfapps.eu20-001.hana.ondemand.com/**", "https://*.cfapps.eu20.hana.ondemand.com/**"]
}
```

I guess this should do the trick. Make sure to rebuild and redeploy your MTA after doing the changes.

**Comment by johnkbarrow** [comment] 2023-06-01 13:38
Hi @beckermarc - thanks for the quick follow-up. It works with the added information to the xs-security-mt.json file. Perhaps given the situation with extension domains, you could add something to the setup readme?

**Comment by beckermarc** [comment] 2023-06-01 13:46
Yes we could add it to the README, but I think I'd like to clarify before if that is really expected behaviour and also really expected to be solved like that. I will try to reach out to the relevant BTP colleagues to clarify that.

**Comment by beckermarc** [comment] 2023-06-21 12:26
I meanwhile learnt that specifying redirect URIs is now mandatory on some landscapes and also the expected behaviour. I have adopted our sample to configure correct redirect URLs by default with this PR: https://github.com/SAP-samples/cloud-cap-samples-java/pull/235
This should solve any future problems and manual configuration, once merged.

**Closed by beckermarc** 2023-06-21 12:26 UTC
