### ISSUE TITLE
Error when building and running application

### ISSUE THREAD

**Issue by docirl** [SAP-samples/cloud-cap-samples-java#236] opened 2023-06-26 15:35 UTC
Hi,

Myself and other colleagues are seeing an error related required cds versions when cloning this repo and running `mvn spring-boot:run`: 

<img width="1385" alt="image" src="https://github.com/SAP-samples/cloud-cap-samples-java/assets/45471079/a29eb1cd-4cd2-4044-a05e-7d487efe9f63">

I have java 17 installed, but others are seeing another error when using java 11.

Please test if this is reproducible to you also. I dont see any specific requirements locally for cds so I dont think local installed versions should be required?

Any help here is appreciated.
Fyi @beckermarc

**Comment by pbusko** [comment] 2023-06-27 06:35
The build error is caused by versioning inconsistencies on CAP side:

```console
$ npm ls @sap/cds
bookshop-java@1.0.0 /tmp/cloud-cap-samples-java
├─┬ @sap/cds-dk@6.8.2 extraneous
│ ├─┬ @sap/cds-mtxs@1.8.2 extraneous
│ │ └── @sap/cds@6.8.2 deduped
│ ├── @sap/cds@6.8.2 extraneous
│ └─┬ @sap/eslint-plugin-cds@2.6.3 extraneous
│   └── @sap/cds@6.8.2 deduped
├─┬ @sap/cds-fiori@1.0.0 extraneous
│ └── @sap/cds@7.0.0 deduped
├─┬ @sap/cds-mtxs@1.9.0 extraneous
│ └── @sap/cds@7.0.0 deduped
└── @sap/cds@7.0.0 extraneous
```

**Comment by c0d1ngm0nk3y** [comment] 2023-06-27 10:23
Is it not enough to change `cds.install-cdsdk.version` in `pom.xml` from `6.7.2` to `7.0.0`?

**Comment by beckermarc** [comment] 2023-06-27 11:26
Will be fixed by updating to @sap/cds-dk 7 as in https://github.com/SAP-samples/cloud-cap-samples-java/pull/237.
Unfortunately installing @sap/cds-mtxs in `1.9.0` brings @sap/cds `7.0.0`, which then conflicts with the previous @sap/cds-dk `6.8.2`.

**Closed** 2023-06-28 14:51 UTC
